### ISSUE TITLE
Unhandled IPv4/IPv6 address overflow for range/prefix queries

### ISSUE THREAD

**Issue by edmonds** [farsightsec/dnstable#13]
IP range and IP prefix queries are internally converted into a start and end key that are passed to `mtbl_source_get_range()`. This requires the end key to be calculated as one more than the ending IP address (otherwise we miss some keys at the top of the range). In the case of a prefix like `255.255.255.0/24` or a range ending in `255.255.255.255`, this causes unsigned integer overflow, and we end up generating the ending key `\x02\x00\x00\x00\x00` (probably we want `\x03` instead), which is prior to the start key, which causes no results to be returned.

There is an analogous case for IPv6 addresses.

**Comment by hstern** [comment]
We can do this with the octet after the address in the key, the rrtype.  We increment \x02\xff\xff\xff\xff\x01 to \x02\xff\xff\xff\xff\x02.
