### ISSUE TITLE
Add Requires: libmtbl line to dnstable/libdnstable.pc.in

### ISSUE THREAD

**Issue by reedjc** [farsightsec/dnstable#32]
Using setup.py to build pydnstable failed like:

In file included from dnstable.c:308:0:
/home/reed/opt/farsight/dnstable-0.10.0/include/dnstable.h:29:18: fatal error: mtbl.h: No such file or directory 
 #include <mtbl.h>

This can be fixed with adding libmtbl to the pydnstable's setup.py pkgconfig check. But pydnstable doesn't have code using mbtl directly. It is a dependency of dnstable so I suggest fixing it here (in dnstable) instead.

**Comment by reedjc** [comment]
See https://people.freedesktop.org/~dbn/pkg-config-guide.html
"If the required libraries support pkg-config, they should be added to Requires  ..."
dnstable uses mtbl.h and libdnstable uses libmtbl.so.1

Example of this in use:

$ PKG_CONFIG_PATH=/home/reed/tmp/dnstable/usr/local/lib/pkgconfig/:/home/reed/opt/farsight/mtbl-1.2.1/lib/pkgconfig/ pkg-config --cflags libdnstable
-I/usr/local/include -I/home/reed/opt/farsight/mtbl-1.2.1/include

I made a branch and will do merge request now.

**Comment by reedjc** [comment]
See pull request 33

**Comment by djw1149** [comment]
Merged pull request 33 after testing
