### ISSUE TITLE
lookup: check for arguments

### ISSUE THREAD

**Issue by reedjc** [farsightsec/dnstable#46]
dnstable_lookup -j rrset missing the owner-label name to lookup results in seg fault in
wdns_reverse_name ().   Maybe wdns_reverse_name() shouldn't core dump when has no valid name?  but dnstable_lookup shouldn't continue that far if missing an argument.

Also core dump if rdata with no second argument. It should have usage output.

**Comment by djw1149** [comment]
Previously fixed on the next branch.

**Comment by reedjc** [comment]
Thanks. I looked and saw change for  rrset. Today I built dependency mtbl next and dnstable from next.

The "-j rrset" missing argument is fixed on next branch.

But problem still exists for rdata:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055cca5e79457 in main (argc=1, argv=0x7ffeca164858)
    at src/dnstable_lookup.c:149
149                     if (strcmp(argv[1], "ip") == 0 && argc == 3) {
(gdb) bt full
#0  0x000055cca5e79457 in main (argc=1, argv=0x7ffeca164858)
    at src/dnstable_lookup.c:149
        __s2 = 0x0
        __result = <optimized out>
        __s2_len = 2
        env_fname = 0x0
        env_setfile = 0x0
        arg_owner_name = 0x0
        arg_rrtype = 0x0
        arg_bailiwick = 0x0
        arg_rdata = 0x0
        m_reader = 0x0
        d_iter = 0x11c00
        d_reader = 0x11c30
        d_query = 0x1
        d_qtype = <optimized out>
        res = <optimized out>
        ch = <optimized out>
        __PRETTY_FUNCTION__ = "main"

**Comment by cmikk** [comment]
Fixed in pr #48
